name: "hoyolab-auto-checkin-bot"

on:
  push:
    branches: [ "main" ]
  schedule:
      - cron: "0 22 * * *"  # 在 UTC 22點執行程式
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # python3 ./check_in.py ${{vars.ltuids}} ${{vars.ltokens}} ${{vars.users}}
