name: "hoyolab-auto-checkin-bot"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./check_in.py ${{secrets.ltuids}} ${{secrets.ltokens}} ${{secrets.users}}